### ISSUE TITLE
我写了个onenav1.0 c++ 后台  貌似你这个是0924的api不一样。

### ISSUE THREAD

**Issue by marklove5102** [maxzhang666/HiNav#1]
～是否会升级api?
我缺浏览器插件源码
1.0占用空间很少哦。！

**Comment by maxzhang666** [comment]
这个API纯粹是为了兼容扒拉的一个浏览器扩展的

版本嘛，我也不知道是啥版本了，暂时凑合用

后续做个油猴版本的，浏览器插件的还是太麻烦，更新一次还要审核

**Comment by marklove5102** [comment]
油猴子的在那分享下啊

**Comment by maxzhang666** [comment]
> 油猴子的在那分享下啊

还没写了、、、咕咕咕咕
